# Generated by Django 4.1.1 on 2022-11-22 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user", old_name="image", new_name="profile_image",
        ),
    ]