# Generated by Django 4.1.3 on 2022-11-25 12:16

from django.db import migrations, models
import filter.utils


class Migration(migrations.Migration):

    dependencies = [
        ("filter", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filterimage",
            name="filter_image",
            field=models.ImageField(upload_to=filter.utils.rename_imagefile_to_uuid),
        ),
    ]
