# Generated by Django 4.1.3 on 2022-11-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filter", "0002_filterimage_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filterimage",
            name="filter_image",
            field=models.ImageField(upload_to="filter"),
        ),
    ]
