# Generated by Django 4.1.3 on 2022-11-23 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("filter", "0002_filterimage_likes"),
    ]

    operations = [
        migrations.CreateModel(
            name="TempImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temp_image", models.ImageField(upload_to="temp")),
                (
                    "user_filter",
                    models.ImageField(null=True, upload_to="user_temp_filter"),
                ),
                (
                    "filter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temp_filter",
                        to="filter.filterimage",
                    ),
                ),
            ],
        ),
    ]
