# Generated by Django 4.1.3 on 2022-11-25 12:12

from django.db import migrations, models
import django.db.models.deletion
import main.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_image', models.ImageField(upload_to=main.utils.rename_imagefile_to_uuid)),
                ('user_filter', models.ImageField(null=True, upload_to=main.utils.rename_userimagefile_to_uuid)),
                ('filter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_filter', to='filter.filterimage')),
            ],
        ),
    ]
