<<<<<<< HEAD
# Generated by Django 4.1.3 on 2022-11-23 13:47
=======
# Generated by Django 4.1.3 on 2022-11-25 06:19
>>>>>>> c9deb7ff041de7f3fb44d064b4753eaf83113e8d

from django.db import migrations, models
import django.db.models.deletion
import main.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('filter', '0001_initial'),
=======
        ("filter", "0001_initial"),
>>>>>>> c9deb7ff041de7f3fb44d064b4753eaf83113e8d
    ]

    operations = [
        migrations.CreateModel(
            name='TempImage',
            fields=[
<<<<<<< HEAD
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_image', models.ImageField(upload_to='temp')),
                ('user_filter', models.ImageField(null=True, upload_to='user_temp_filter')),
                ('filter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temp_filter', to='filter.filterimage')),
=======
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "temp_image",
                    models.ImageField(upload_to=main.utils.rename_imagefile_to_uuid),
                ),
                (
                    "user_filter",
                    models.ImageField(
                        null=True, upload_to=main.utils.rename_userimagefile_to_uuid
                    ),
                ),
                (
                    "filter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temp_filter",
                        to="filter.filterimage",
                    ),
                ),
>>>>>>> c9deb7ff041de7f3fb44d064b4753eaf83113e8d
            ],
        ),
    ]
