# Generated by Django 4.1.3 on 2022-11-24 12:32

from django.db import migrations, models
import main.utils


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempimage',
            name='temp_image',
            field=models.ImageField(upload_to=main.utils.rename_imagefile_to_uuid),
        ),
    ]
