# Generated by Django 4.1.3 on 2022-11-23 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("filter", "0002_filterimage_likes"),
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tempimage",
            name="filter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="temp_filter",
                to="filter.filterimage",
            ),
        ),
    ]
